# -*- coding: utf-8 -*-
"""DiogoGaldino_e_FernandoHermers_teste-api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14-oKe8JUopAK_y1noZSBpAncRJ55JglA
"""

import requests
import os

#Pede ao usuário um código de área.
var = input("Informe um código de área:")

#Concatena a URL e o parâmetro necessário (DDD informado pelo usuário)
url = "https://www.servicos.gov.br/api/v1/servicos/" +var

# Realiza a solicitação HTTP POST com os parâmetros e cabeçalhos
response = requests.get(url, headers={'Content-Type': 'application/json'})

# Verifica se a resposta foi bem sucedida (código 200)
if response.status_code == 200:

    data = response.json()

    # Imprime  o conteúdo da resposta  sem nenhum tratamento.
    #print(data)

    #Imprime o conteúdo da resposta de forma que o usuário consiga interpretar.
    #imprime somente a chave  'state'.
    print("ID:", data['resposta']['id'])
    print("Nome:", data['resposta']['nome'])
    print("Sigla:", data['resposta']['sigla'])
    print("Descrição:", data['resposta']['descricao'])
    print("Contato:", data['resposta']['contato'])
   
    #imprime todos os itens dentro da chave 'cities'.
    #for item in data['cities']:
    #  print("Cidade:",item)
   
else:
    # Imprime o código de erro HTTP
    print("Erro HTTP %d - %s" % (response.status_code, response.reason))
   
os.system("PAUSE")

#546

import requests
import os

#Pede ao usuário um código de área.
var = input("Informe um código de área:")

#Concatena a URL e o parâmetro necessário (DDD informado pelo usuário)
url = "https://www.servicos.gov.br/api/v1/paginas-orgao/" +var

# Realiza a solicitação HTTP POST com os parâmetros e cabeçalhos
response = requests.get(url, headers={'Content-Type': 'application/json'})

# Verifica se a resposta foi bem sucedida (código 200)
if response.status_code == 200:

    data = response.json()

    # Imprime  o conteúdo da resposta  sem nenhum tratamento.
    #print(data)

    #Imprime o conteúdo da resposta de forma que o usuário consiga interpretar.
    #imprime somente a chave  'state'.
    print("ID:", data['resposta']['id'])
    print("URL:", data['resposta']['url'])
    print("Nome:", data['resposta']['nome'])
    print("Conteúdo:", data['resposta']['conteudo'])
    print("Contato:", data['resposta']['contato'])
   
    #imprime todos os itens dentro da chave 'cities'.
    #for item in data['resposta']:
    #    print("Resposta:",item)
   
else:
    # Imprime o código de erro HTTP
    print("Erro HTTP %d - %s" % (response.status_code, response.reason))
   
os.system("PAUSE")

#6

import requests
import os

#Pede ao usuário um código de área.
var = input("Informe um código de área:")

#Concatena a URL e o parâmetro necessário (DDD informado pelo usuário)
url = "https://servicodados.ibge.gov.br/api/v1/paises/indicadores/" +var

# Realiza a solicitação HTTP POST com os parâmetros e cabeçalhos
response = requests.get(url, headers={'Content-Type': 'application/json'})

# Verifica se a resposta foi bem sucedida (código 200)
if response.status_code == 200:

    data = response.json()

    # Imprime  o conteúdo da resposta  sem nenhum tratamento.
    print(data)

    #Imprime o conteúdo da resposta de forma que o usuário consiga interpretar.
    #imprime somente a chave  'state'.
    #print("resposta:", data['resposta'])
    #print("ID:", data['']['id'])
    #print("URL:", data['url'])
    #print("Nome:", data['nome'])
    #print("Conteúdo:", data['conteudo'])
    #print("ID:", data['id'])
   
    #imprime todos os itens dentro da chave 'cities'.
    for item in data:
      print("ID:",item['id'])
      print("Indicador:",item['indicador'])
      print("Unidade:",item['unidade'])
      
    # data2 = (item['unidade'])
    # for unidade in data2:
    #   print(unidade)

      
        
else:
    # Imprime o código de erro HTTP
    print("Erro HTTP %d - %s" % (response.status_code, response.reason))
   
os.system("PAUSE")

#77819|77820